# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - release/*
      - hotfix/*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - name: Checkout main branch
        run: |
          git checkout main
          git pull
      - name: Merge and push
        run: |
          git merge --no-ff "${GITHUB_REF#refs/heads/}"
          git push origin main
      - name: Checkout develop branch
        run: |
          git checkout develop
          git pull
      - name: Merge main into develop and push
        run: |
          git merge --no-ff main
          git push origin develop